Fixing release

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -21,7 +21,7 @@ jobs:
   release:
     if: ${{ github.event_name == 'push' && github.ref_name == 'main' ||  github.ref_name == 'release' }}
     runs-on: ubuntu-latest
-    needs: build
+#    needs: build
     steps:
     - name: Checkout
       uses: actions/checkout@v4
@@ -36,6 +36,8 @@ jobs:
       run: |
         set -e
         task_processor_version=$(grep "<task-processor.version>" pom.xml | grep -v '<!--' | sed -E 's/.*<task-processor.version>([^<]+)<\/task-processor.version>.*/\1/')
+        [ -z "$task_processor_version" ] && echo "Failed to extract task-processor.version from pom.xml" && exit 1
+        
         release_version="v${task_processor_version}"
         if gh release view "$release_version" > /dev/null; then
           release_version="${release_version}-${run_number}"
